kind: pipeline
name: default

steps:
  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: Hosts
      delete: true
      source: ./docs
      target: /root/apps/a-programmers-guide-to-english/docs
      key:
        from_secret: Key
